version: '3'

services:
  web:
    build: .
    command: sh -c "python task_management/manage.py migrate && python task_management/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - app_network

  postgres:
    image: postgres:16.4
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app_network

  redis:
    image: redis:7.0-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
  redis_data:
